### ISSUE TITLE
Split Developing & Building a Drupal site from scratch to frontend & backend

### ISSUE THREAD

**Issue by hedleysmith** [OpenDrupal/opendrupal#24]
During planning of the Drupal Apprenticeship we decided on a unit "Developing & Building a Drupal site from scratch".

As I've been building the curriculum in GitHub I split this out into [frontend](https://github.com/OpenDrupal/opendrupal/tree/master/frontend) and [backend](https://github.com/OpenDrupal/opendrupal/tree/master/backend) as it seemed to make more sense and should keep units similar in size.

Does anyone have any ideas about whether this is a good / bad idea?

**Comment by the-greenman** [comment]
As long as we feel that this is not adding too much extra effort to our V1 plan, I think it is the right path.

**Comment by hedleysmith** [comment]
I think it will be clearer as to where to put learning material when building and maintaining the curriculum, and we'll just have to make sure we don't overload the units so it's still achievable within a year. 

Thanks Peter, I'll close this off now
